name: app_calculator
description: calculator application

version: 1.0.9+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  math_expressions: ^2.2.0
  webview_flutter: ^2.0.14
  mime: ^1.0.0
  petitparser: ^4.3.0
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  flutter_icons: ^1.1.0
  url_launcher: ^6.0.12
  flutter_launcher_icons: ^0.9.2
  linalg: ^0.4.0
  fl_chart: ^0.40.0
  google_mobile_ads: ^0.13.4
  font_awesome_flutter: ^9.1.0
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  cloud_firestore: ^2.5.3
  app_tracking_transparency: ^2.0.1
  firebase_messaging: ^10.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "assets/images/launcher_icon_background.png"
  adaptive_icon_foreground: "assets/images/launcher_icon_foreground.png"



flutter:

  uses-material-design: true

  assets:
    - assets/html/homepage.html
    - assets/html/jquery-3.4.1.min.js
    - assets/html/mathquill.css
    - assets/html/mathquill.min.js

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times.ttf
    - family: Keyboard
      fonts:
        - asset: assets/fonts/Keyboard-Icon.ttf
    - family: Josefin
      fonts:
          - asset: assets/fonts/JosefinSans.ttf
    - family: GemunuLibre
      fonts:
          - asset: assets/fonts/GemunuLibre.ttf
